services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/app
      # Add this to avoid overwriting node_modules in the container by the host's empty one
      - api_node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    env_file:
      - ./api/.env
    # command: npm run dev # Or your actual start command

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    # If your frontend .env file contains variables needed at build time or by compose itself
    # you might need to uncomment and adjust the following:
    # env_file:
    #   - ./.env

  db:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT_ON_HOST:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_INIT_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_INIT_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_INIT_NAME:-progress_calendar_db}
    env_file:
      - .env

volumes:
  pgdata:
  api_node_modules: {}
  frontend_node_modules: {} 