# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application's code
COPY . .

# The command to start the Vite development server will be specified in docker-compose.yml
# EXPOSE 5173 # Already exposed in docker-compose

CMD ["npm", "run", "dev", "--", "--host"] 